mutation MutationModel($environmentId: ID!, $apiId: String!, $apiIdPlural: String!, $displayName: String!) {
  createModel(
    data: {
        environmentId: $environmentId,
        apiId: $apiId,
        apiIdPlural: $apiIdPlural,
        displayName: $displayName
    }
  ) {
    migration {
      createdAt
      errors
      finishedAt
      id
      name
      operationType
      resourceId
      status
    }
  }
}